In [13]:
import numpy as np


matrix = np.random.randint(1,5, size=(5,4))
matrix


array([[2, 1, 4, 2],
       [2, 3, 1, 3],
       [2, 4, 2, 2],
       [2, 4, 2, 2],
       [2, 1, 3, 4]], dtype=int32)

In [14]:
transposed_matrix = matrix.T
transposed_matrix

array([[2, 2, 2, 2, 2],
       [1, 3, 4, 4, 1],
       [4, 1, 2, 2, 3],
       [2, 3, 2, 2, 4]], dtype=int32)

In [16]:
column_mean = np.mean(matrix, axis=0 )
row_std_deviation = np.std(matrix, axis=1)
column_mean


array([2. , 2.6, 2.4, 2.6])

In [17]:
row_std_deviation

array([1.08972474, 0.8291562 , 0.8660254 , 0.8660254 , 1.11803399])

In [18]:
dot_prod = np.dot(matrix, transposed_matrix)
dot_prod


array([[25, 17, 20, 20, 25],
       [17, 23, 24, 24, 22],
       [20, 24, 28, 28, 22],
       [20, 24, 28, 28, 22],
       [25, 22, 22, 22, 30]], dtype=int32)